### ISSUE TITLE
Where can I get this model?

### ISSUE THREAD

**Issue by violetdenim** [xushilin1/RAP-SAM#1]
Hello!
I'm trying to reproduce your solution and I get this error in yoso_head.py, line 364:
`ov_path = os.path.join(os.path.expanduser('~/.cache/embd'), f"{ov_classifier_name}.pth")`

I searched online for the backbone `convnext_large_d_320_CocoPanopticOVDataset.pth` but haven't found any.

Could you please provide a link in readme, or at least, please send it to me (kristinazipa@yandex.ru)

As I understood, it corresponds to ConvNeXt-L results in your paper.

**Comment by xushilin1** [comment]
Hello!
Thank you for your interest in our work. Please pull the latest code and generate the classifier using the following command:
```
PYTHONPATH='.' python tools/gen_cls.py configs/rap_sam/rap_sam_convl_12e_adaptor.py
```
I will send you the generated classifier to your email later.
Thank you for your attention.

**Comment by violetdenim** [comment]
I pre-loaded Coco-dataset and youtube-VIS-2019 datasets. Do I need to perform some additional preprocessing on them?

I'm getting this error:
```
[2024-01-22 12:11:12,295] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
01/22 12:11:13 - mmengine - INFO - Loaded convnext_large_d_320 model config.
01/22 12:11:15 - mmengine - INFO - Loading pretrained convnext_large_d_320 weights (laion2b_s29b_b131k_ft_soup).
01/22 12:11:15 - mmengine - INFO - Loaded convnext_large_d_320 model config.
01/22 12:11:17 - mmengine - INFO - Loading pretrained convnext_large_d_320 weights (laion2b_s29b_b131k_ft_soup).
01/22 12:11:18 - mmengine - INFO - Init Config for convnext_large_d_320
01/22 12:11:18 - mmengine - INFO - {'type': 'clip_pretrain', 'checkpoint': 'laion2b_s29b_b131k_ft_soup'}
01/22 12:11:18 - mmengine - INFO - ------------Concat_CocoPanopticOVDataset_YouTubeVISDataset_2019------------
01/22 12:11:18 - mmengine - WARNING - Attribute `_fully_initialized` is not defined in <class 'mmengine.dataset.dataset_wrapper.RepeatDataset'> or `type(obj)._fully_initialized is False, `full_init` will be called and <class 'mmengine.dataset.dataset_wrapper.RepeatDataset'>._fully_initialized will be set to True
loading annotations into memory...
Done (t=2.26s)
creating index...
index created!
01/22 12:11:28 - mmengine - INFO - |---dataset#1 --> name: CocoPanopticOVDataset; length: 117266; repeat times: 1
loading annotations into memory...
Done (t=3.76s)
creating index...
Traceback (most recent call last):
  File "/home/zipa/Projects/RAP-SAM/tools/gen_cls.py", line 189, in <module>
    main()
  File "/home/zipa/Projects/RAP-SAM/tools/gen_cls.py", line 117, in main
    dataset = DATASETS.build(dataset_cfg)
  File "/home/zipa/anaconda3/envs/py10/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zipa/anaconda3/envs/py10/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zipa/Projects/RAP-SAM/seg/datasets/concat_dataset.py", line 141, in __init__
    f"|---dataset#{idx + 1} --> name: {dataset_type}; length: {len(dataset)}; repeat times: {times}",
  File "/home/zipa/anaconda3/envs/py10/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 112, in wrapper
    obj.full_init()  # type: ignore
  File "/home/zipa/anaconda3/envs/py10/lib/python3.10/site-packages/mmengine/dataset/dataset_wrapper.py", line 251, in full_init
    self.dataset.full_init()
  File "/home/zipa/anaconda3/envs/py10/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 298, in full_init
    self.data_list = self.load_data_list()
  File "/home/zipa/anaconda3/envs/py10/lib/python3.10/site-packages/mmdet/datasets/base_video_dataset.py", line 35, in load_data_list
    self.coco = COCO(local_path)
  File "/home/zipa/anaconda3/envs/py10/lib/python3.10/site-packages/mmdet/datasets/api_wrappers/coco_api.py", line 25, in __init__
    super().__init__(annotation_file=annotation_file)
  File "/home/zipa/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 86, in __init__
    self.createIndex()
  File "/home/zipa/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 95, in createIndex
    imgToAnns[ann['image_id']].append(ann)
KeyError: 'image_id'
```

**Comment by xushilin1** [comment]
Sorry for the error. I will fix the bug later, and you can download the file here. [ckpt](https://1drv.ms/u/c/12a1b84edebf20f7/EVjJu546FCtAko-aqlsb11IBPMKIIuIrm8blwpP1sDyD6w?e=LvALSA)
