### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by Masrur02** [xushilin1/RAP-SAM#5]
Hi,
I am using this command

**./tools/dist_test.sh configs/rap_sam/eval_rap_sam_coco.py $CKPT $NUM_GPUS**
**./tools/dist_test.sh configs/rap_sam/eval_rap_sam_coco.py convnext_large_d_320_CocoPanopticOVDataset.pth 1**

```
but I am getting this error
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1344890) of binary: /home/soicroot/miniconda3/envs/rap/bin/python
Traceback (most recent call last):
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-18_15:35:07
  host      : soicroot
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1344890)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html




```

Even I use this rapsam_r50_12e.pth checkpoint, still I get the same error

Can you please guide me how to debug it?

**Comment by xushilin1** [comment]
I cannot find useful error information about this issue. Could you please provide me with more detailed error information and the environment you used?

**Comment by HarborYuan** [comment]
Hi @Masrur02 ,

Thanks for your interest in our work.

I can confirm that your command is correct. It seems that the bug is caused by the torch elastic rather than the test script. Could you please try to re-install the PyTorch? I think the bug may be caused by the environment.
