### ISSUE TITLE
Single image

### ISSUE THREAD

**Issue by zhujun3753** [xushilin1/RAP-SAM#6]
How can I test on single image?

**Comment by lxtGH** [comment]
@xushilin1 Please address this issue by adding demo.py

**Comment by lucierynd** [comment]
@zhujun3753 Did you manage to test it on a single image ?

**Comment by chuanchuan-qin** [comment]
> How can I test on single image?

Have you solved this problem?

**Comment by xushilin1** [comment]
Sorry for the late reply.
I have updated the code and provided demo.py You can test a single image using the following command.

```
python demo/demo.py demo/demo.jpg configs/rap_sam/eval_rap_sam_coco.py --weights rapsam_r50_12e.pth
```

**Comment by KEVEONz** [comment]
After I run the command 

> python demo/demo.py demo/demo.jpg configs/rap_sam/eval_rap_sam_coco.py --weights rapsam_r50_12e.pth

An error message appears

`Traceback (most recent call last):
  File "/storage-root/datasets/duyinglong/SA1B/code/RMP-SAM/demo/demo.py", line 192, in <module>
    main()
  File "/storage-root/datasets/duyinglong/SA1B/code/RMP-SAM/demo/demo.py", line 184, in main
    inferencer(**call_args)
  File "/storage-root/datasets/duyinglong/SA1B/code/mmdetection-main/mmdet/apis/det_inferencer.py", line 404, in __call__
    visualization = self.visualize(
                    ^^^^^^^^^^^^^^^
  File "/storage-root/datasets/duyinglong/SA1B/code/mmdetection-main/mmdet/apis/det_inferencer.py", line 491, in visualize
    self.visualizer.add_datasample(
  File "/root/miniconda3/lib/python3.11/site-packages/mmengine/dist/utils.py", line 427, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/storage-root/datasets/duyinglong/SA1B/code/mmdetection-main/mmdet/visualization/local_visualizer.py", line 494, in add_datasample
    pred_img_data = self._draw_panoptic_seg(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage-root/datasets/duyinglong/SA1B/code/mmdetection-main/mmdet/visualization/local_visualizer.py", line 288, in _draw_panoptic_seg
    colors = [mask_palette[label] for label in labels]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage-root/datasets/duyinglong/SA1B/code/mmdetection-main/mmdet/visualization/local_visualizer.py", line 288, in <listcomp>
    colors = [mask_palette[label] for label in labels]
              ~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range`

Please how can I solve this problem?
